### ISSUE TITLE
 Target class [Chartello\Http\Controllers\Chartello\Http\Controllers\DashboardsController] does not exist. 

### ISSUE THREAD

**Issue by Irwanripansyahh** [chartello/chartello#9]
getting eror when instal on laravel 8

![image](https://github.com/chartello/chartello/assets/54163903/28510746-5d2c-4e68-b34e-e43e274f5893)

**Comment by matt-daneshvar** [comment]
Hey @Irwanripansyahh, thanks for trying out Chartello and for reporting. Unfortunately, there are multiple parts of the package that aren't compatible with Laravel 8, and given that [Laravel 8 has reached its end of life](https://laravel.com/docs/10.x/releases), I don't think we'll be adding backward support for it. 

I'll update the docs to make sure this is communicated upfront.
